### ISSUE TITLE
Change tests to always use TransactionManager for creating TransactionContexts

### ISSUE THREAD

**Issue by julianmenzler** [d-justen/hyrise#33]
Then uncomment `Fail`-instruction in `new_transaction_context()`

**Comment by julianmenzler** [comment]
I adjusted some tests to the TransactionManager for creating TransactionManager.
Following tests require TransactionContexts to be constructed by hand though.
<img width="714" alt="image" src="https://user-images.githubusercontent.com/9380917/52818884-2f6fb600-30a8-11e9-8d1a-19e7a262495b.png">

**Comment by engelfa** [comment]
Can we close this because the transactions register themselves when created?

**Comment by julianmenzler** [comment]
I think so, but it is a long time ago. I'll look into this when I finish the TransactionManager PR later today.

**Comment by julianmenzler** [comment]
Solved, in a different way: Tests can still create `TransactionContext` objects on their own. But these will automatically register themselves at the `TransactionManager` from their constructor.
